<a href="https://colab.research.google.com/github/HSJung93/Pytorch_Practice/blob/master/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Tensor

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
x = torch.empty(5, 4)
print(x)

tensor([[1.0774e-35, 0.0000e+00, 7.0065e-44, 6.7262e-44],
        [6.3058e-44, 6.7262e-44, 7.9874e-44, 6.3058e-44],
        [7.0065e-44, 7.8473e-44, 1.1771e-43, 6.8664e-44],
        [7.0065e-44, 8.1275e-44, 7.0065e-44, 7.7071e-44],
        [8.1275e-44, 7.0065e-44, 7.9874e-44, 6.4460e-44]])


In [ ]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2)

tensor([0., 0.])

In [ ]:
torch.rand(5, 6)

tensor([[0.7664, 0.6283, 0.4970, 0.4406, 0.6160, 0.5643],
        [0.7479, 0.6351, 0.2462, 0.0120, 0.6967, 0.5282],
        [0.4584, 0.6201, 0.8591, 0.1014, 0.2376, 0.3748],
        [0.7914, 0.2098, 0.4803, 0.5506, 0.5014, 0.5871],
        [0.2392, 0.6070, 0.4017, 0.1647, 0.2233, 0.2751]])

In [ ]:
l = [13, 4]
r = np.array([4, 56, 7])

In [ ]:
torch.tensor(l)

tensor([13,  4])

In [ ]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.9944, 0.2625],
        [0.1342, 0.7259]])
tensor([[0.6170, 0.1901],
        [0.8998, 0.1817]])


In [ ]:
x+y

tensor([[1.6114, 0.4526],
        [1.0340, 0.9076]])

In [ ]:
torch.add(x, y)

tensor([[1.6114, 0.4526],
        [1.0340, 0.9076]])

In [ ]:
y.add(x)

tensor([[1.6114, 0.4526],
        [1.0340, 0.9076]])

In [ ]:
y.add_(x)

tensor([[1.6114, 0.4526],
        [1.0340, 0.9076]])

In [ ]:
y

tensor([[1.6114, 0.4526],
        [1.0340, 0.9076]])

In [ ]:
y[1, 1]

tensor(0.9076)

In [ ]:
y[:, 1]

tensor([0.4526, 0.9076])

In [ ]:
x = torch.rand(8, 8)
print(x)

tensor([[0.4231, 0.8871, 0.9321, 0.8236, 0.2434, 0.4370, 0.6570, 0.2761],
        [0.9591, 0.4284, 0.3859, 0.1380, 0.5607, 0.3962, 0.8077, 0.2151],
        [0.5777, 0.5301, 0.4986, 0.0179, 0.2619, 0.7954, 0.9269, 0.7559],
        [0.8936, 0.8812, 0.8311, 0.7130, 0.9472, 0.9249, 0.5150, 0.3959],
        [0.3385, 0.2596, 0.1365, 0.6660, 0.5531, 0.3971, 0.6447, 0.3884],
        [0.1170, 0.1487, 0.0032, 0.2627, 0.5426, 0.1882, 0.2070, 0.2585],
        [0.6991, 0.6740, 0.6799, 0.8977, 0.2230, 0.5724, 0.7736, 0.8987],
        [0.8198, 0.8675, 0.3444, 0.4106, 0.5751, 0.2009, 0.8886, 0.6210]])


In [ ]:
x.view(64)

tensor([0.4231, 0.8871, 0.9321, 0.8236, 0.2434, 0.4370, 0.6570, 0.2761, 0.9591,
        0.4284, 0.3859, 0.1380, 0.5607, 0.3962, 0.8077, 0.2151, 0.5777, 0.5301,
        0.4986, 0.0179, 0.2619, 0.7954, 0.9269, 0.7559, 0.8936, 0.8812, 0.8311,
        0.7130, 0.9472, 0.9249, 0.5150, 0.3959, 0.3385, 0.2596, 0.1365, 0.6660,
        0.5531, 0.3971, 0.6447, 0.3884, 0.1170, 0.1487, 0.0032, 0.2627, 0.5426,
        0.1882, 0.2070, 0.2585, 0.6991, 0.6740, 0.6799, 0.8977, 0.2230, 0.5724,
        0.7736, 0.8987, 0.8198, 0.8675, 0.3444, 0.4106, 0.5751, 0.2009, 0.8886,
        0.6210])

In [ ]:
x.view(4, 16)

tensor([[0.4231, 0.8871, 0.9321, 0.8236, 0.2434, 0.4370, 0.6570, 0.2761, 0.9591,
         0.4284, 0.3859, 0.1380, 0.5607, 0.3962, 0.8077, 0.2151],
        [0.5777, 0.5301, 0.4986, 0.0179, 0.2619, 0.7954, 0.9269, 0.7559, 0.8936,
         0.8812, 0.8311, 0.7130, 0.9472, 0.9249, 0.5150, 0.3959],
        [0.3385, 0.2596, 0.1365, 0.6660, 0.5531, 0.3971, 0.6447, 0.3884, 0.1170,
         0.1487, 0.0032, 0.2627, 0.5426, 0.1882, 0.2070, 0.2585],
        [0.6991, 0.6740, 0.6799, 0.8977, 0.2230, 0.5724, 0.7736, 0.8987, 0.8198,
         0.8675, 0.3444, 0.4106, 0.5751, 0.2009, 0.8886, 0.6210]])

In [ ]:
x.view(2, -1) # conv. layer -> preconnected layer

tensor([[0.4231, 0.8871, 0.9321, 0.8236, 0.2434, 0.4370, 0.6570, 0.2761, 0.9591,
         0.4284, 0.3859, 0.1380, 0.5607, 0.3962, 0.8077, 0.2151, 0.5777, 0.5301,
         0.4986, 0.0179, 0.2619, 0.7954, 0.9269, 0.7559, 0.8936, 0.8812, 0.8311,
         0.7130, 0.9472, 0.9249, 0.5150, 0.3959],
        [0.3385, 0.2596, 0.1365, 0.6660, 0.5531, 0.3971, 0.6447, 0.3884, 0.1170,
         0.1487, 0.0032, 0.2627, 0.5426, 0.1882, 0.2070, 0.2585, 0.6991, 0.6740,
         0.6799, 0.8977, 0.2230, 0.5724, 0.7736, 0.8987, 0.8198, 0.8675, 0.3444,
         0.4106, 0.5751, 0.2009, 0.8886, 0.6210]])

In [ ]:
y = x.numpy()
print(y)

[[0.42307085 0.88713855 0.93206066 0.82363254 0.2434277  0.43702996
  0.6570364  0.2760985 ]
 [0.9591395  0.42839044 0.3859306  0.13803434 0.5607135  0.39623183
  0.8076959  0.21505082]
 [0.5776534  0.5300652  0.49856532 0.01794177 0.26190966 0.7953814
  0.9268865  0.7559341 ]
 [0.89361846 0.88122326 0.831094   0.7130099  0.94722795 0.9249465
  0.51496065 0.3958891 ]
 [0.33848047 0.25955665 0.13645375 0.66604793 0.5531364  0.39711654
  0.64474446 0.38836527]
 [0.11703724 0.14868718 0.00323194 0.26265    0.5425867  0.18815327
  0.20702678 0.25853068]
 [0.6990646  0.6739981  0.6799373  0.89769435 0.22303498 0.57237875
  0.7735591  0.8986936 ]
 [0.8197676  0.8675233  0.34437126 0.41058153 0.575127   0.20093405
  0.8885701  0.6209567 ]]


In [ ]:
type(y)

numpy.ndarray

In [ ]:
x = torch.ones(1)

In [ ]:
x

tensor([1.])

In [ ]:
x.item() #loss function, value

1.0

# 2. Back propagation

In [ ]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [ ]:
z = 2*y**2
res = z.mean()

In [ ]:
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [ ]:
res

tensor(8., grad_fn=<MeanBackward0>)

In [ ]:
# d(res)/dx_i = x_i+1
# res = (z_1+...+z_4)/4
# z_i = 2(x_i+1)**2

res.backward()

In [ ]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
import torch.nn as nn
import torch.nn.functional as f 

# 3. Import data and customizing

In [ ]:
import torch
import torchvision
import torchvision.transforms as tr
from torch.utils.data import DataLoader, Dataset
import numpy as np

## 3.1. 파이토치 제공 데이터 사용

In [ ]:
transf = tr.Compose([tr.Resize(8), tr.ToTensor()])
# Transforms on PIL Image
# Pad, Grayscale, RandomCrop, Normalize ...
# Transfroms on torch.*Tensor - tensor image
# torchvision.transforms.ToPILImage(mode=None)...


In [ ]:
trainset = torchvision.datasets.CIFAR10(root = './sample_data', train = True, download = True, transform = transf)
testset = torchvision.datasets.CIFAR10(root = './sample_data', train = False, download = True, transform = transf)

Extracting ./sample_data/cifar-10-python.tar.gz to ./sample_data
Files already downloaded and verified


In [ ]:
trainset[0][0].size()

torch.Size([3, 8, 8])

In [ ]:
trainset[0][1]

6

In [ ]:
trainloader = DataLoader(trainset, batch_size = 50, shuffle= True, num_workers = 2)
testloader = DataLoader(testset, batch_size = 50, shuffle= True, num_workers = 2)

In [ ]:
len(trainloader) # total 50000 data, batch_size is 50, so batch is 1000.

1000

In [ ]:
dataiter = iter(trainloader)
images, labels = dataiter.next()

In [ ]:
images.size() # batch size, channel #, size

torch.Size([50, 3, 8, 8])

## 3.2. 같은 클래스 별 폴더 이미지 데이터 이용

In [ ]:
# ./class/tiger ./class/lion
transf = tr.Compose([tr.Resize(16), tr.ToTensor()])
trainset = torchvision.datasets.ImageFolder(root='./class', transform=transf)
trainloader = DataLoader(trainset, batch_size = 10, shuffle = False, num_workder = 2)
print(len(trainloader))
print(trainset[0][0].size())

FileNotFoundError: ignored

## 3.3 개인 데이터 사용(2 types)

In [ ]:
# import preprocessing

train_images = np.random.randint(256, size=(20, 32, 32, 3))
train_labels = np.random.randint(2, size = (20, 1) )

# preprocessing
# train_images, train_labels = preprocessing(train_images, train_labels)

print(train_images.shape, train_labels.shape)

(20, 32, 32, 3) (20, 1)


In [ ]:
class TensorData(Dataset):

    def __init__(self, x_data, y_data):
        self.x_data = torch.FloatTensor(x_data)
        self.x_data = self.x_data.permute(0, 3, 1, 2) # 이미지 개수, 채널 수, 이미지 너비, 높이
        self.y_data = torch.LongTensor(y_data)
        self.len = self.y_data.shape[0]

    def __getitem__(self, index):

        return self.x_data[index], self.y_data[index]

    def __len__(self):

        return self.len



In [ ]:
train_data = TensorData(train_images, train_labels)
train_loader = DataLoader(train_data, batch_size = 10, shuffle = True)

In [ ]:
train_data[0][0].size()

torch.Size([3, 32, 32])

In [ ]:
dataiter = iter(train_loader)
images, labels = dataiter.next()

In [ ]:
images.size()

torch.Size([10, 3, 32, 32])

from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self):

    def __gettime__(self, index):

    def __len__(self):
        

In [ ]:
# memorize this format
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self, x_data, y_data, transform = None):
        self.x_data = x_data
        self.y_data = y_data
        self.transform = transform
        self.len = len(y_data)

    def __getitem__(self, index):
        sample = self.x_data[index], self.y_data[index]

        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        return self.len

class ToTensor:
  
    def __call__(self, sample):
        inputs, labels = sample
        inputs = torch.FloatTensor(inputs)
        inputs = inputs.permute(2, 0, 1)
        return inputs, torch.LongTensor(labels)

class LinearTensor:

    def __init__(self, slope = 1, bias = 0):
        self.slope = slope
        self.bias = bias

    def __call__(self, sample):
        inputs, labels = sample
        inputs = self.slope * inputs + self.bias
        return inputs, labels

In [ ]:
trans = tr.Compose([ToTensor(), LinearTensor(2, 5)]) # vs. transf = tr.Compose([tr.Resize(8), tr.ToTensor()])

ds1 = MyDataset(train_images, train_labels, transform = trans)
train_loader1 = DataLoader(ds1, batch_size = 10, shuffle = True)

In [ ]:
first_data = ds1[0]
features, labels = first_data
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [ ]:
dataiter1 = iter(train_loader1)
images1, labels1 = dataiter1.next()

In [ ]:
images1

tensor([[[[133., 499., 193.,  ..., 201., 389.,  91.],
          [271., 377., 181.,  ..., 291., 499., 387.],
          [379., 455.,   9.,  ...,  15., 325., 477.],
          ...,
          [269., 291.,  31.,  ...,  17., 119.,  15.],
          [485., 259., 163.,  ..., 213.,  79., 201.],
          [481., 429., 339.,  ..., 315., 103., 213.]],

         [[327., 175., 255.,  ..., 473., 249.,  51.],
          [247., 297., 381.,  ...,  67., 347.,  99.],
          [111., 503., 375.,  ..., 379.,  89., 301.],
          ...,
          [391., 297.,  55.,  ..., 173., 117., 421.],
          [419., 183., 335.,  ..., 361.,  17., 161.],
          [473., 445., 389.,  ...,  43., 287.,  49.]],

         [[469., 235., 511.,  ..., 411., 317.,  13.],
          [403., 239., 181.,  ..., 431.,  33., 371.],
          [235.,  21., 391.,  ..., 479.,  37., 205.],
          ...,
          [305., 405., 333.,  ..., 313., 307., 159.],
          [ 55., 409., 129.,  ..., 399., 473., 377.],
          [353., 507., 405.,  ...

In [ ]:
class MyDataset(Dataset):

    def __init__(self, x_data, y_data, transform = None):
        self.x_data = x_data
        self.y_data = y_data
        self.transform = transform
        self.len = len(y_data)

    def __getitem__(self, index):
        sample = self.x_data[index], self.y_data[index]

        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        return self.len

class MyTransform:

    def __call__(self, sample):
        inputs, labels = sample
        inputs = torch.FloatTensor(inputs)
        inputs = inputs.permute(2, 0, 1)
        labels = torch.FloatTensor(labels)

        transf = tr.Compose([tr.ToPILImage(), tr.Resize(128), tr.ToTensor() ])
        final_output = transf(inputs)

        return final_output, labels

In [ ]:
ds2 = MyDataset(train_images, train_labels, transform = MyTransform() )
train_loader2 = DataLoader(ds2, batch_size = 10, shuffle = True)

In [ ]:
first_data = ds2[0]
features, labels = first_data
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [ ]:
dataiter2 = iter(train_loader2)
images2, labels2 = dataiter2.next()

In [ ]:
images2.size()

torch.Size([10, 3, 128, 128])

In [ ]:
images2

tensor([[[[0.0275, 0.0275, 0.0275,  ..., 0.7843, 0.7882, 0.7882],
          [0.0275, 0.0275, 0.0275,  ..., 0.7843, 0.7882, 0.7882],
          [0.1137, 0.1137, 0.1098,  ..., 0.7216, 0.7294, 0.7294],
          ...,
          [0.4000, 0.4000, 0.4275,  ..., 0.1059, 0.0863, 0.0863],
          [0.3529, 0.3529, 0.3961,  ..., 0.0627, 0.0431, 0.0431],
          [0.3529, 0.3529, 0.3961,  ..., 0.0627, 0.0431, 0.0431]],

         [[0.6039, 0.6039, 0.5725,  ..., 0.7765, 0.8196, 0.8196],
          [0.6039, 0.6039, 0.5725,  ..., 0.7765, 0.8196, 0.8196],
          [0.6078, 0.6078, 0.5725,  ..., 0.6784, 0.7176, 0.7176],
          ...,
          [0.6353, 0.6353, 0.6314,  ..., 0.4980, 0.5020, 0.5020],
          [0.6941, 0.6941, 0.6863,  ..., 0.5373, 0.5412, 0.5412],
          [0.6941, 0.6941, 0.6863,  ..., 0.5373, 0.5412, 0.5412]],

         [[0.4745, 0.4745, 0.5333,  ..., 0.2471, 0.2039, 0.2039],
          [0.4745, 0.4745, 0.5333,  ..., 0.2471, 0.2039, 0.2039],
          [0.5137, 0.5137, 0.5569,  ..., 0

# 4. Build and Save Basic Models

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

## 4.1. Load data set

In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
)

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size = 8,
                                          shuffle=True, num_workers = 2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)

testloader = torch.utils.data.DataLoader(testset, batch_size = 8, 
                                         shuffle = False, num_workers = 2)

classes = ( 'plane', 'car', 'bird', 'cat', 
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Files already downloaded and verified
Files already downloaded and verified


## 4.2. Build a model

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5) # in order to plug in x to fully connected we flat the x with view funtion 
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()

In [ ]:
print(net)

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


## 4.3. Implement the model with training set

In [ ]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss() # classifying 
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [ ]:
for epoch in range(1): # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0): 
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parmeter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999: # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')

[1,  2000] loss: 2.200
[1,  4000] loss: 1.815
[1,  6000] loss: 1.613
Finished Training


### 4.4. Save the trained model

In [ ]:
PATH = './cifar_net.pth'
torch.save(net.state_dict(), PATH)

### 4.5 Load the pre-trained model

In [ ]:
net = Net()
net.load_state_dict((torch.load(PATH)))

<All keys matched successfully>

### output은 미니배치의 결과가 산출되기 때문에 for 문을 통해서 test 전체의 예측값을 구해야 한다.

In [ ]:
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images) # output is the vector of length 10 
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print("Accuracy of the network on the 10000 test images: %d %%" % (100 * correct / total))

Accuracy of the network on the 10000 test images: 43 %


# 5. Network-based Deep Transfer Learning

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms # data preprocessing
from torch.utils.data import DataLoader # mini-batch

import torch.nn as nn # loss
import torch.optim as optim # optimizer

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive
